server:
  port: 50000
spring:
  datasource:
    url: jdbc:mysql://112.126.83.141:63300/HommeCloudUser?useSSL=false&&allowPublicKeyRetrieval=true
    username: root
    password: Mz5152526@
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: userservice
  cloud:
    nacos:
      server-addr: 192.168.3.234:8848

mybatis:
  type-aliases-package: top.Cloud.Homme.user.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    Cloud.Homme: debug

userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
ribbon:
  eager-load:
    enabled: true
    clients:
      - docservice
feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
